### ISSUE TITLE
Burn: numbers are not correct

### ISSUE THREAD

**Issue by reuptaken** [Uniswap/uniswap-v3-info#93]
**Bug Description**
For small amounts 0 is displayed even if swaps of similar size report non-zero values

<img width="1182" alt="Zrzut ekranu 2021-06-2 o 10 12 08" src="https://user-images.githubusercontent.com/26765602/120447880-4cb91300-c38b-11eb-842d-4afd2c2003c9.png">

Transaction:

https://etherscan.io/tx/0x324eb68a31ae7d60752eb8a4fc6b68c73fbdc4a139f46ba65832c321d057cba5

**Comment by ianlapham** [comment]
This is actually correct - although maybe we should hide this because its somewhat useless - its basically a burn that is attached to some other methods like collect 

<img width="856" alt="Screen Shot 2021-06-09 at 10 37 00 PM" src="https://user-images.githubusercontent.com/17100331/121455901-36a2e800-c973-11eb-9d5a-55b045434a5d.png">
